# Generated by Django 3.1.2 on 2020-12-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
