# Generated by Django 3.1.2 on 2021-01-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210106_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaidaccesstoken',
            name='item',
        ),
        migrations.DeleteModel(
            name='PlaidItemIds',
        ),
    ]
