# Generated by Django 3.1.2 on 2021-03-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210111_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidaccesstoken',
            name='institution_id',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
